name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
        
---  
        
- name: Python Tox on Fedora
  # You may pin to the exact commit or the version.
  # uses: fedora-python/tox-github-action@9f7d1fff53d7384568baa0ddd748e0c35b102b82
  uses: fedora-python/tox-github-action@v0.4
  with:
    # Tox environment to run the tests on
    tox_env: # default is py38
    # Space separated packages to install via dnf install (can contain options)
    dnf_install: # optional, default is 
---        
        
- name: Setup Python
  uses: actions/setup-python@v2.2.2
  with:
    # Version range or exact version of a Python version to use, using SemVer's version range syntax.
    python-version: # optional, default is 3.x
    # The target architecture (x86, x64) of the Python interpreter.
    architecture: # optional
    # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
    token: # optional, default is ${{ github.token }}
    
